export interface DestinationData {
  type: "city" | "country";
  name: string;
  slug: string;
  country: string;
  countrySlug: string;
  continent: string;
  continentSlug: string;
  short: string;
  description: string;
  whatToSee: string[];
  gastronomy: string[];
  activities: string[];
  priceRange: string;
  image: string;
  badge?: string;
  rating: number;
  bestTime: string;
  avgFlightPrice: string;
  readTime: string;
  keywords: string[];
  cities?: string[];
  parentSlug?: string;
  transport?: string;
  travelTips?: string[];
  neighborhoods?: { name: string; desc: string }[];
  dayTrips?: string[];
  budget?: string;
}

const base: Omit<DestinationData, "type" | "slug" | "name" | "short" | "description" | "whatToSee" | "gastronomy" | "activities" | "priceRange" | "image" | "rating" | "bestTime" | "avgFlightPrice" | "readTime" | "keywords"> = {
  country: "",
  countrySlug: "",
  continent: "",
  continentSlug: "",
};

export const destinations: DestinationData[] = [
  // ─────────────────────────────────────
  // EUROPA
  // ─────────────────────────────────────

  // ── España ──
  {
    ...base,
    type: "country",
    name: "España",
    slug: "espana",
    country: "España",
    countrySlug: "espana",
    continent: "Europa",
    continentSlug: "europa",
    short: "Sol, playa, cultura y gastronomía de clase mundial.",
    description: "España es uno de los destinos turísticos más populares del mundo. Desde las playas del Mediterráneo hasta la arquitectura modernista de Barcelona, pasando por la rica historia de Madrid y la tradición flamenca de Andalucía, ofrece una diversidad inigualable.",
    whatToSee: ["Museo del Prado en Madrid", "Sagrada Familia en Barcelona", "Alhambra de Granada", "Catedral de Sevilla y Giralda"],
    gastronomy: ["Paella valenciana", "Jamón ibérico", "Tapas y pinchos", "Vinos de Rioja y Ribera del Duero"],
    activities: ["Ruta del flamenco en Andalucía", "Camino de Santiago", "Playas de la Costa Brava", "Festival de San Fermín"],
    priceRange: "60€ - 180€",
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200&h=800&fit=crop",
    badge: "Top",
    rating: 4.7,
    bestTime: "Abril - Octubre",
    avgFlightPrice: "60€",
    readTime: "10 min",
    keywords: ["hoteles en España", "viajar a España", "destinos España", "vacaciones España"],
    cities: ["barcelona", "madrid", "sevilla", "valencia", "granada", "bilbao", "malaga", "palma"],
  },
  {
    type: "city",
    name: "Barcelona",
    slug: "barcelona",
    country: "España",
    countrySlug: "espana",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "espana",
    short: "Playas, Gaudí y la mejor gastronomía mediterránea.",
    description: "Barcelona combina playas urbanas con arquitectura modernista. La ciudad de Gaudí ofrece desde la Sagrada Familia hasta el Park Güell. Su escena gastronómica, playas y vida nocturna la convierten en un destino versátil.",
    whatToSee: ["Sagrada Familia y Park Güell", "La Rambla y Barrio Gòtic", "Barceloneta y playas", "Casa Batlló y Pedrera"],
    gastronomy: ["Tapas y paella", "Mercat de la Boqueria", "Crema catalana", "Cava y vinos del Penedès"],
    activities: ["Ruta modernismo de Gaudí", "Playas y chiringuitos", "Tour gastronómico del Born", "Visita a Montserrat"],
    priceRange: "80€ - 200€",
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "60€",
    readTime: "7 min",
    keywords: ["hoteles en Barcelona", "dónde dormir en Barcelona", "hoteles playa Barcelona", "hoteles Barcelona centro"],
    transport: "Metro eficiente (TMB) con 8 líneas que cubren toda la ciudad. También hay buses, tranvía y el aeropuerto conecta por tren y autobús. El taxi cuesta unos 25-35€ del aeropuerto al centro.",
    travelTips: ["Evita las horas punta en metro (8-9h y 18-19h)", "Compra la tarjeta T-Casual para 10 viajes (mejor que billete sencillo)", "Cuidado con carteristas en La Rambla y metro", "Muchos museos tienen entrada gratis los domingos", "El tiempo es impredecible, lleva siempre un jersey"],
    neighborhoods: [
      { name: "Eixample", desc: "La zona más elegante con edificios modernistas y amplias avenidas. Ideal para alojarse." },
      { name: "Barrio Gótico", desc: "El casco histórico con calles medievales, plazas escondidas y ambiente turístico." },
      { name: "El Born", desc: "Bohemio y trendy, con galerías de arte, boutiques y los mejores bares de tapas." },
      { name: "Barceloneta", desc: "Barrio marinero junto a la playa, ideal para amantes del mar y el pescado fresco." },
    ],
    dayTrips: ["Montserrat - Monasterio benedictino a 1h en tren", "Sitges - Pueblo costero con playas y ambiente festivo", "Costa Brava - Calas escondidas y paisajes espectaculares"],
    budget: "Viaje económico: 70€/día (hostal + menú del día). Gama media: 140€/día (hotel 3* + restaurante). Lujo: 300€+/día (hotel 5* + cena en restaurante Michelin).",
  },
  {
    type: "city",
    name: "Madrid",
    slug: "madrid",
    country: "España",
    countrySlug: "espana",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "espana",
    short: "Arte, tapas y la vida nocturna más vibrante de Europa.",
    description: "Madrid es una ciudad vibrante que nunca duerme. Desde el Triángulo del Arte con el Prado, Reina Sofía y Thyssen hasta el bullicio de la Plaza Mayor, pasando por sus mercados gastronómicos y la animada vida nocturna.",
    whatToSee: ["Museo del Prado y Triángulo del Arte", "Palacio Real y Plaza Mayor", "Parque del Retiro y Puerta de Alcalá", "Templo de Debod y Gran Vía"],
    gastronomy: ["Cocido madrileño y callos", "Bocadillo de calamares", "Tapas en La Latina y Cava Baja", "Churros con chocolate en San Ginés"],
    activities: ["Ruta de museos", "Atardecer en Templo de Debod", "Mercado de San Miguel", "Espectáculo flamenco"],
    priceRange: "70€ - 180€",
    image: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=1200&h=800&fit=crop",
    badge: "Cultural",
    rating: 4.6,
    bestTime: "Marzo - Junio",
    avgFlightPrice: "50€",
    readTime: "7 min",
    keywords: ["hoteles en Madrid", "dónde dormir en Madrid", "hoteles Madrid centro", "hoteles baratos Madrid"],
    transport: "Metro de Madrid (12 líneas) es el mejor medio. También hay Cercanías, autobuses urbanos (EMT) y el aeropuerto conecta por metro (línea 8). Taxi desde aeropuerto unos 30€.",
    travelTips: ["El metro funciona hasta la 1:30h, los fines de semana hay servicio nocturno", "Sol y Plaza Mayor son el centro neurálgico, perfecto para empezar", "Los museos como el Prado son gratis de 18:00 a 20:00h", "El barrio de La Latina es ideal para tapear", "Lleva efectivo, algunos bares pequeños no aceptan tarjeta"],
    neighborhoods: [
      { name: "Sol y Centro", desc: "El corazón de Madrid con la Puerta del Sol, Plaza Mayor y Gran Vía." },
      { name: "Malasaña", desc: "Barrio alternativo con tiendas vintage, bares de moda y ambiente joven." },
      { name: "La Latina", desc: "El mejor barrio para tapear, con callejuelas llenas de bares y tabernas." },
      { name: "Salamanca", desc: "Zona elegante con tiendas de lujo, restaurantes sofisticados y embajadas." },
    ],
    dayTrips: ["Toledo - Ciudad imperial a 30min en tren AVE", "Segovia - Acueducto romano y Alcázar a 1h", "El Escorial - Monasterio y palacio real a 45min"],
    budget: "Económico: 65€/día. Medio: 130€/día. Lujo: 280€+/día.",
  },
  {
    type: "city",
    name: "Sevilla",
    slug: "sevilla",
    country: "España",
    countrySlug: "espana",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "espana",
    short: "Flamenco, naranjos y la esencia más auténtica de Andalucía.",
    description: "Sevilla es el corazón de Andalucía. Su imponente Catedral, el Real Alcázar y la Plaza de España son solo el comienzo. Sus calles estrechas en Santa Cruz, el aroma a azahar y el flamenco más auténtico crean una atmósfera única.",
    whatToSee: ["Catedral y Giralda", "Real Alcázar", "Plaza de España", "Barrio de Santa Cruz y Metropol Parasol"],
    gastronomy: ["Gazpacho andaluz", "Pescaíto frito", "Tapas en Triana", "Vinos de Jerez y manzanilla"],
    activities: ["Espectáculo flamenco en Triana", "Paseo en barco por el Guadalquivir", "Visita a la Plaza de Toros", "Excursión a Itálica"],
    priceRange: "60€ - 140€",
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200&h=800&fit=crop",
    rating: 4.7,
    bestTime: "Marzo - Mayo",
    avgFlightPrice: "55€",
    readTime: "6 min",
    keywords: ["hoteles en Sevilla", "dónde dormir en Sevilla", "hoteles Sevilla centro", "hoteles Sevilla baratos"],
    transport: "Sevilla tiene tranvía (Metrocentro) y autobuses urbanos (Tussam). El aeropuerto conecta por autobús (EA) cada 30min. Andando se llega a casi todo en el centro.",
    travelTips: ["Visita la Giralda y la Catedral temprano para evitar colas", "El Barrio de Santa Cruz es perfecto para perderse sin mapa", "Prueba las tapas en la calle Betis de Triana", "El Alcázar tiene colas de hasta 2h, reserva online", "Lleva calzado cómodo, las calles son adoquinadas"],
    neighborhoods: [
      { name: "Santa Cruz", desc: "El barrio judío con estrechas callejuelas llenas de flores y patios." },
      { name: "Triana", desc: "Barrio marinero al otro lado del río, cuna del flamenco y las cerámicas." },
      { name: "Centro", desc: "Alrededor de la Catedral, con tiendas y restaurantes turísticos." },
    ],
    dayTrips: ["Itálica - Ruinas romanas a 20min", "Ronda - Ciudad del Tajo a 1.5h", "Jerez - Vino y caballos a 1h"],
    budget: "Económico: 55€/día. Medio: 110€/día. Lujo: 250€+/día.",
  },
  {
    type: "city",
    name: "Valencia",
    slug: "valencia",
    country: "España",
    countrySlug: "espana",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "espana",
    short: "Paella, Ciudad de las Artes y playas mediterráneas.",
    description: "Valencia fusiona tradición y vanguardia. Su Ciudad de las Artes y las Ciencias contrasta con el casco antiguo medieval. Es la cuna de la paella y ofrece playas urbanas como la Malvarrosa.",
    whatToSee: ["Ciudad de las Artes y las Ciencias", "Mercado Central y Lonja de la Seda", "Playa de la Malvarrosa", "Barrio del Carmen"],
    gastronomy: ["Paella valenciana auténtica", "Horchata y fartons", "Mercado Central y tapas", "Arroces del senyoret"],
    activities: ["Ruta de la paella", "Paseo por la Albufera", "Visita al Oceanogràfic", "Ciclismo por el Jardín del Turia"],
    priceRange: "60€ - 130€",
    image: "https://images.unsplash.com/photo-1595867818082-083862f3d630?w=1200&h=800&fit=crop",
    rating: 4.5,
    bestTime: "Abril - Septiembre",
    avgFlightPrice: "50€",
    readTime: "6 min",
    keywords: ["hoteles en Valencia", "dónde dormir en Valencia", "hoteles Valencia centro", "hoteles playa Valencia"],
    transport: "Metro (6 líneas) y autobuses (EMT) conectan toda la ciudad. El aeropuerto conecta por metro (línea 3) en 20min. Hay carril bici por toda la ciudad.",
    travelTips: ["La Ciudad de las Artes se ve mejor al atardecer", "La playa de la Malvarrosa está a 15min en bici del centro", "El Mercado Central cierra los domingos", "Prueba la paella auténtica en El Cabanyal", "El Jardín del Turia es perfecto para pasear o ir en bici"],
    neighborhoods: [
      { name: "Ciutat Vella", desc: "El casco histórico con la Catedral, la Lonja y el Mercado Central." },
      { name: "El Carmen", desc: "Barrio alternativo con arte urbano, galerías y bares de copas." },
      { name: "Ruzafa", desc: "Barrio de moda con restaurantes trendy, mercadillos y ambiente cultural." },
    ],
    dayTrips: ["Albufera - Parque natural y arrozales a 20min", "Xàtiva - Ciudad histórica a 1h", "Peñíscola - Castillo templario a 1.5h"],
    budget: "Económico: 50€/día. Medio: 100€/día. Lujo: 220€+/día.",
  },
  {
    type: "city",
    name: "Granada",
    slug: "granada",
    country: "España",
    countrySlug: "espana",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "espana",
    short: "La Alhambra, el Albaicín y las vistas a Sierra Nevada.",
    description: "Granada enamora con su Alhambra, el palacio nazarí más impresionante del mundo. El barrio del Albaicín con sus miradores, el Sacromonte con sus cuevas flamencas y las vistas a Sierra Nevada crean una experiencia única.",
    whatToSee: ["Alhambra y Generalife", "Albaicín y Mirador de San Nicolás", "Catedral y Capilla Real", "Sacromonte y Zambra"],
    gastronomy: ["Tapas gratis con la consumición", "Habitas con jamón", "Piononos de Santa Fe", "Tortilla del Sacromonte"],
    activities: ["Visita guiada a la Alhambra", "Atardecer en el Albaicín", "Esquí en Sierra Nevada", "Baños árabes"],
    priceRange: "50€ - 120€",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=800&fit=crop",
    badge: "Imprescindible",
    rating: 4.8,
    bestTime: "Marzo - Junio",
    avgFlightPrice: "60€",
    readTime: "6 min",
    keywords: ["hoteles en Granada", "dónde dormir en Granada", "hoteles Granada centro", "hoteles baratos Granada"],
    transport: "Granada tiene autobuses urbanos y un metro ligero. El aeropuerto conecta por autobús (Granada Airport Bus). La Alhambra se alcanza andando desde el centro pero la cuesta es pronunciada.",
    travelTips: ["Reserva la Alhambra con 2-3 semanas de antelación, se agota rápido", "Las tapas gratis con cada bebida son tradición en Granada", "El mirador de San Nicolás tiene las mejores vistas de la Alhambra al atardecer", "El Albaicín tiene calles muy empinadas, lleva calzado cómodo", "En invierno se puede esquiar en Sierra Nevada a 30min"],
    neighborhoods: [
      { name: "Albaicín", desc: "Barrio árabe con calles estrechas, miradores espectaculares y ambiente único." },
      { name: "Centro", desc: "Alrededor de la Catedral con tiendas, restaurantes y vida nocturna." },
      { name: "Realejo", desc: "Antiguo barrio judío, ahora lleno de arte urbano y bares alternativos." },
    ],
    dayTrips: ["Sierra Nevada - Esquí o senderismo a 30min", "La Alpujarra - Pueblos blancos a 1h"],
    budget: "Económico: 45€/día (tapas gratis incluido). Medio: 90€/día. Lujo: 200€+/día.",
  },
  {
    type: "city",
    name: "Bilbao",
    slug: "bilbao",
    country: "España",
    countrySlug: "espana",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "espana",
    short: "Guggenheim, pintxos y el verde del País Vasco.",
    description: "Bilbao resurgió con el Museo Guggenheim como emblema. Su casco viejo, los pintxos en el Mercado de la Ribera y el verde de sus alrededores la convierten en un destino único en el norte de España.",
    whatToSee: ["Museo Guggenheim", "Casco Viejo y Siete Calles", "Catedral de Santiago", "Puente Colgante y Ría"],
    gastronomy: ["Pintxos en el Casco Viejo", "Bacalao al pil pil", "Txakoli y vinos vascos", "Mercado de la Ribera"],
    activities: ["Tour del arte y arquitectura", "Pintxo route por el Casco Viejo", "Excursión a San Juan de Gaztelugatxe", "Visita a las bodegas de Rioja Alavesa"],
    priceRange: "70€ - 160€",
    image: "https://images.unsplash.com/photo-1533387520709-752d83de3630?w=1200&h=800&fit=crop",
    rating: 4.5,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "65€",
    readTime: "6 min",
    keywords: ["hoteles en Bilbao", "dónde dormir en Bilbao", "hoteles Bilbao centro", "hoteles baratos Bilbao"],
    transport: "Metro de Bilbao limpio y eficiente (3 líneas). También hay tranvía y funicular a Artxanda. El aeropuerto conecta por autobús (Bizkaibus) cada 20min.",
    travelTips: ["El Guggenheim se ve impresionante desde el Puente de La Salve", "Los pintxos en el Casco Viejo son obligatorios, prueba en la Plaza Nueva", "El tranvía es gratis si tienes billete de metro", "El Mercado de la Ribera es el mercado cubierto más grande de Europa", "San Juan de Gaztelugatxe requiere caminata de 30min cuesta arriba"],
    neighborhoods: [
      { name: "Casco Viejo", desc: "Las Siete Calles con bares de pintxos, tiendas y la Catedral de Santiago." },
      { name: "Indautxu", desc: "Zona moderna con tiendas, restaurantes y la plaza Moyúa." },
      { name: "Abandoibarra", desc: "Zona del Guggenheim con arquitectura contemporánea y paseos junto a la ría." },
    ],
    dayTrips: ["San Juan de Gaztelugatxe - Ermita en un islote a 30min", "Rioja Alavesa - Bodegas y viñedos a 1h"],
    budget: "Económico: 60€/día. Medio: 120€/día. Lujo: 260€+/día.",
  },
  {
    type: "city",
    name: "Málaga",
    slug: "malaga",
    country: "España",
    countrySlug: "espana",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "espana",
    short: "Sol, museos y el mejor pescaíto de la Costa del Sol.",
    description: "Málaga es la capital de la Costa del Sol. Ciudad natal de Picasso, ofrece una mezcla perfecta de playas, museos de primer nivel, Alcazaba árabe y una animada vida nocturna en el puerto.",
    whatToSee: ["Alcazaba y Gibralfaro", "Museo Picasso", "Catedral de Málaga", "Playas de la Malagueta"],
    gastronomy: ["Pescaíto frito y espetos de sardinas", "Porra antequerana", "Vinos de Málaga", "Helados artesanales"],
    activities: ["Ruta de museos", "Día de playa en la Malagueta", "Caminito del Rey", "Visita a Ronda y pueblos blancos"],
    priceRange: "55€ - 130€",
    image: "https://images.unsplash.com/photo-1514214246283-d427a95c5d2f?w=1200&h=800&fit=crop",
    rating: 4.4,
    bestTime: "Abril - Octubre",
    avgFlightPrice: "50€",
    readTime: "6 min",
    keywords: ["hoteles en Málaga", "dónde dormir en Málaga", "hoteles playa Málaga", "hoteles centro Málaga"],
    transport: "Aeropuerto muy bien conectado por Cercanías (12min al centro) y autobús. Metro de Málaga (2 líneas) y autobuses urbanos (EMT). Taxi del aeropuerto al centro unos 20€.",
    travelTips: ["El Museo Picasso es gratis los domingos por la tarde", "Caminito del Rey hay que reservar con semanas de antelación", "Los espetos de sardinas son típicos en los chiringuitos de playa", "La Alcazaba tiene vistas espectaculares al puerto", "Málaga tiene más de 30 museos, muchos gratuitos"],
    neighborhoods: [
      { name: "Centro Histórico", desc: "La zona antigua con la Catedral, museos y calle Larios." },
      { name: "La Malagueta", desc: "Junto a la playa más famosa, con chiringuitos y paseo marítimo." },
      { name: "Soho", desc: "Barrio de arte urbano con galerías y restaurantes alternativos." },
    ],
    dayTrips: ["Ronda - Ciudad del Tajo y puente nuevo a 1.5h", "Caminito del Rey - Pasarela en acantilados a 1h"],
    budget: "Económico: 50€/día. Medio: 100€/día. Lujo: 220€+/día.",
  },
  {
    type: "city",
    name: "Palma de Mallorca",
    slug: "palma",
    country: "España",
    countrySlug: "espana",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "espana",
    short: "Playas paradisíacas, calas escondidas y vida mediterránea.",
    description: "Palma es la joya de las Baleares. Su imponente Catedral frente al mar, el casco antiguo con calles empedradas y las calas de aguas turquesas la convierten en un destino mediterráneo de primer orden.",
    whatToSee: ["Catedral de Mallorca", "Castillo de Bellver", "Palacio Real de La Almudaina", "Casco Antiguo y La Lonja"],
    gastronomy: ["Ensaimada mallorquina", "Pa amb oli", "Sobrasada y queso mahonés", "Arroz brut y caldereta"],
    activities: ["Navegar a calas escondidas", "Catedral y casco histórico", "Visita a la Serra de Tramuntana", "Mercado del Olivar"],
    priceRange: "70€ - 200€",
    image: "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=1200&h=800&fit=crop",
    badge: "Sol y Playa",
    rating: 4.5,
    bestTime: "Mayo - Octubre",
    avgFlightPrice: "55€",
    readTime: "7 min",
    keywords: ["hoteles en Palma", "dónde dormir en Mallorca", "hoteles playa Palma", "hoteles Palma centro"],
    transport: "Aeropuerto de Son Sant Joan conecta por autobús (A1) al centro. Buses urbanos (EMT) y tren a Sóller. Alquilar coche es la mejor opción para explorar la isla.",
    travelTips: ["Alquila coche para ver calas escondidas, el transporte público no llega a todas", "La Catedral ilumina el mar al atardecer desde el Paseo Marítimo", "La Serra de Tramuntana es Patrimonio de la Humanidad y tiene rutas increíbles", "Evita agosto si buscas tranquilidad, es temporada alta", "Prueba la ensaimada en el Forn des Teatre"],
    neighborhoods: [
      { name: "Centro Histórico", desc: "Calles empedradas, Palacio Real y la Catedral como emblema." },
      { name: "Santa Catalina", desc: "Barrio de moda con restaurantes, mercados y ambiente cosmopolita." },
      { name: "Portixol", desc: "Zona portuaria con paseo marítimo, bares y vistas al mar." },
    ],
    dayTrips: ["Sóller - Tren histórico a través de la montaña", "Valldemossa - Pueblo de montaña con historia de Chopin", "Cala d'Or - Calas turquesas al este de la isla"],
    budget: "Económico: 65€/día. Medio: 130€/día. Lujo: 280€+/día (temporada alta).",
  },

  // ── Francia ──
  {
    type: "country",
    name: "Francia",
    slug: "francia",
    country: "Francia",
    countrySlug: "francia",
    continent: "Europa",
    continentSlug: "europa",
    short: "Arte, gastronomía y romance en cada rincón.",
    description: "Francia es el destino más visitado del mundo. París, la Ciudad de la Luz, enamora con sus monumentos icónicos. Pero más allá de la capital, Francia ofrece desde los castillos del Loira hasta la Riviera francesa, los Alpes y la Provenza.",
    whatToSee: ["Torre Eiffel y Louvre", "Castillos del Loira", "Costa Azul y Niza", "Mont Saint-Michel"],
    gastronomy: ["Croissants y baguettes", "Quesos y vinos franceses", "Ratatouille provenzal", "Crêpes bretonas"],
    activities: ["Ruta del vino en Burdeos", "Esquí en los Alpes", "Crucero por el Sena", "Tour de la Provenza"],
    priceRange: "80€ - 250€",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=800&fit=crop",
    badge: "Top",
    rating: 4.8,
    bestTime: "Abril - Octubre",
    avgFlightPrice: "120€",
    readTime: "12 min",
    keywords: ["hoteles en Francia", "viajar a Francia", "destinos Francia", "vacaciones Francia"],
    cities: ["paris", "lyon", "marsella", "niza", "bordeaux"],
  },
  {
    type: "city",
    name: "París",
    slug: "paris",
    country: "Francia",
    countrySlug: "francia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "francia",
    short: "La ciudad de la luz con barrios icónicos y gastronomía de primer nivel.",
    description: "París es la capital de Francia, conocida mundialmente como la Ciudad de la Luz. Con emblemáticos monumentos como la Torre Eiffel, el Museo del Louvre y la Catedral de Notre-Dame, ofrece una combinación única de historia, arte, moda y gastronomía.",
    whatToSee: ["Torre Eiffel y Campos de Marte", "Museo del Louvre", "Notre-Dame y Sainte-Chapelle", "Arco de Triunfo y Campos Elíseos", "Montmartre y Sacré-Cœur", "Palacio de Versalles"],
    gastronomy: ["Croissants y pâtisserie francesa", "Quesos artesanales y vinos", "Cafés de Montmartre", "Restaurantes Michelin en Le Marais"],
    activities: ["Paseo en barco por el Sena", "Compra en Galerías Lafayette", "Espectáculo en Moulin Rouge", "Picnic en Jardín de Luxembourg"],
    priceRange: "120€ - 220€",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=800&fit=crop",
    badge: "Top",
    rating: 4.8,
    bestTime: "Abril - Junio",
    avgFlightPrice: "150€",
    readTime: "8 min",
    keywords: ["hoteles en París", "dónde dormir en París", "barrios de París", "hoteles baratos París"],
    transport: "Metro (16 líneas) cubre toda la ciudad. RER conecta aeropuertos y suburbios. Pase Navigo semanal por 30€. El taxi del aeropuerto al centro 50-60€ fijo.",
    travelTips: ["El Museo del Louvre tiene entrada gratis el primer viernes de cada mes", "El metro cierra a la 1:15h, los fines de semana hasta las 2:15h", "Montmartre merece la visita al amanecer sin multitudes", "Los cafés en terrazas cuestan el doble que en el interior", "Para la Torre Eiffel, reserva online con 1 mes de antelación"],
    neighborhoods: [
      { name: "Le Marais", desc: "Barrio histórico judío, hoy lleno de boutiques, galerías y la mejor vida nocturna." },
      { name: "Saint-Germain", desc: "Elegancia parisina con cafés míticos, librerías y tiendas de lujo." },
      { name: "Montmartre", desc: "Barrio bohemio con el Sacré-Cœur, vistas panorámicas y ambiente de artista." },
      { name: "Champs-Élysées", desc: "La avenida más famosa del mundo, con tiendas de lujo y el Arco de Triunfo." },
    ],
    dayTrips: ["Versalles - Palacio y jardines a 40min en RER", "Disneyland Paris - 45min en RER A"],
    budget: "Económico: 90€/día. Medio: 180€/día. Lujo: 400€+/día.",
  },
  {
    type: "city",
    name: "Lyon",
    slug: "lyon",
    country: "Francia",
    countrySlug: "francia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "francia",
    short: "Capital gastronómica de Francia con un casco histórico medieval.",
    description: "Lyon es considerada la capital gastronómica de Francia. Su casco histórico, Vieux Lyon, es Patrimonio de la Humanidad. Entre sus traboules, bouchons lyonnais y el Festival de las Luces, Lyon cautiva a todo viajero.",
    whatToSee: ["Vieux Lyon y traboules", "Basílica de Fourvière", "Place Bellecour", "Museo de Bellas Artes"],
    gastronomy: ["Bouchons lyonnais", "Quenelles y andouillette", "Vinos del Beaujolais", "Président y chocolates"],
    activities: ["Ruta gastronómica por los bouchons", "Paseo por las orillas del Ródano", "Visita al anfiteatro romano", "Festival de las Luces en diciembre"],
    priceRange: "70€ - 150€",
    image: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200&h=800&fit=crop",
    rating: 4.5,
    bestTime: "Abril - Junio",
    avgFlightPrice: "100€",
    readTime: "6 min",
    keywords: ["hoteles en Lyon", "dónde dormir en Lyon", "hoteles Lyon centro", "hoteles baratos Lyon"],
    transport: "Metro (4 líneas), tranvía y funicular. Aeropuerto Lyon-Saint Exupéry conecta por tren Rhônexpress en 30min (16€). La ciudad es muy walkable.",
    travelTips: ["El Festival de las Luces (8 diciembre) es espectacular pero hoteles se llenan meses antes", "Los bouchons son restaurantes típicos lyoneses, busca los auténticos con la etiqueta 'Bouchon Lyonnais'", "Vieux Lyon es ideal para perderse por sus traboules (pasajes secretos)", "El Museo de Bellas Artes es uno de los mejores de Francia"],
    neighborhoods: [
      { name: "Vieux Lyon", desc: "Barrio medieval con traboules, iglesias y restaurantes tradicionales." },
      { name: "Presqu'île", desc: "Entre el Ródano y el Saona, con tiendas, teatros y la Place Bellecour." },
      { name: "Croix-Rousse", desc: "Barrio de artistas con mercados al aire libre y vistas panorámicas." },
    ],
    dayTrips: ["Beaujolais - Ruta del vino a 30min", "Annecy - Venecia de los Alpes a 1.5h"],
    budget: "Económico: 70€/día. Medio: 140€/día. Lujo: 300€+/día.",
  },
  {
    type: "city",
    name: "Marsella",
    slug: "marsella",
    country: "Francia",
    countrySlug: "francia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "francia",
    short: "Puerto mediterráneo vibrante con cultura y calanques.",
    description: "Marsella es la puerta al Mediterráneo. Su puerto viejo, el barrio Le Panier, la basílica de Notre-Dame de la Garde y las calanques de aguas turquesas la convierten en un destino único, multicultural y lleno de vida.",
    whatToSee: ["Puerto Viejo y Le Panier", "Notre-Dame de la Garde", "Calanques de Cassis", "MUCEM y Fort Saint-Jean"],
    gastronomy: ["Bouillabaisse tradicional", "Pastis y anís", "Pescado a la parrilla", "Mercado de Noailles"],
    activities: ["Excursión a las Calanques", "Paseo en barco al Castillo de If", "Mercado de pescado", "Visita a Aix-en-Provence"],
    priceRange: "65€ - 140€",
    image: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=1200&h=800&fit=crop",
    rating: 4.4,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "90€",
    readTime: "6 min",
    keywords: ["hoteles en Marsella", "dónde dormir en Marsella", "hoteles Marsella centro", "hoteles baratos Marsella"],
    transport: "Metro (2 líneas), tranvía y autobuses. Aeropuerto conecta por autobús (L91) en 30min. Ferris a Córcega y Argelia desde el Puerto Viejo.",
    travelTips: ["Las Calanques son imprescindibles, mejor ir en kayak o barco", "El MUCEM es gratuito para menores de 26 años", "El barrio Le Panier es el más antiguo, ideal para callejear", "La bouillabaisse es el plato estrella pero pide precio antes de pedirla"],
    neighborhoods: [
      { name: "Le Panier", desc: "El barrio más antiguo con calles estrechas, arte callejero y galerías." },
      { name: "Puerto Viejo", desc: "El puerto histórico con barcos de pesca, restaurantes de marisco y el MUCEM." },
      { name: "Cours Julien", desc: "Barrio alternativo con grafitis, tiendas de diseño y bares de moda." },
    ],
    dayTrips: ["Calanques - Kayak o senderismo por calas turquesas", "Cassis - Pueblo pesquero y viñedos a 30min"],
    budget: "Económico: 65€/día. Medio: 130€/día. Lujo: 280€+/día.",
  },
  {
    type: "city",
    name: "Niza",
    slug: "niza",
    country: "Francia",
    countrySlug: "francia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "francia",
    short: "La perla de la Costa Azul con playas y glamour.",
    description: "Niza es la joya de la Riviera francesa. Su Paseo de los Ingleses, la Promenade des Anglais, sus playas de guijarros y el casco antiguo con mercados de flores la convierten en el destino por excelencia de la Costa Azul.",
    whatToSee: ["Promenade des Anglais", "Vieille Ville y Cours Saleya", "Castillo de Niza", "Museo Matisse y Chagall"],
    gastronomy: ["Socca y pissaladière", "Farinata y pan bagnat", "Vinos de Bellet", "Frutas confitadas"],
    activities: ["Baño en la Costa Azul", "Paseo por el Puerto", "Excursión a Mónaco y Cannes", "Mercado de flores"],
    priceRange: "90€ - 200€",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "130€",
    readTime: "6 min",
    keywords: ["hoteles en Niza", "dónde dormir en Niza", "hoteles playa Niza", "hoteles Costa Azul"],
    transport: "Aeropuerto está en la ciudad, conectado por tranvía y autobús. Trenes TER conectan toda la Costa Azul. El tranvía es eficiente y barato.",
    travelTips: ["La Promenade des Anglais es ideal para caminar al atardecer", "El Mercado de flores Cours Saleya cierra a las 17:30", "Desde Niza puedes visitar Mónaco en tren por 8€", "Las playas son de guijarros, lleva zapatos de agua", "El casco antiguo tiene los mejores restaurantes, busca en calles secundarias"],
    neighborhoods: [
      { name: "Vieille Ville", desc: "El casco antiguo con el mercado Cours Saleya, calles estrechas y bares." },
      { name: "Promenade des Anglais", desc: "La avenida costera con playas, hoteles lujosos y paseo marítimo." },
      { name: "Cimiez", desc: "Barrio residencial con ruinas romanas, museos y vistas panorámicas." },
    ],
    dayTrips: ["Mónaco - El principado a 25min en tren", "Cannes - Festival y playas a 30min en tren"],
    budget: "Económico: 80€/día. Medio: 160€/día. Lujo: 350€+/día.",
  },
  {
    type: "city",
    name: "Burdeos",
    slug: "bordeaux",
    country: "Francia",
    countrySlug: "francia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "francia",
    short: "Capital mundial del vino con arquitectura clásica.",
    description: "Burdeos es la capital mundial del vino. Su centro histórico, declarado Patrimonio de la Humanidad, brilla con edificios clásicos de piedra dorada. Los viñedos circundantes producen algunos de los mejores vinos del planeta.",
    whatToSee: ["Place de la Bourse y Espejo de Agua", "Cité du Vin", "Catedral de Saint-André", "Barrio de Saint-Pierre"],
    gastronomy: ["Vinos de Burdeos", "Canelés bordelais", "Entrecôte a la bordelesa", "Ostras de Arcachon"],
    activities: ["Ruta del vino en Saint-Émilion", "Cata en Cité du Vin", "Paseo por la Garonne", "Dune du Pilat"],
    priceRange: "70€ - 160€",
    image: "https://images.unsplash.com/photo-1559511260-66a68e2a7ed0?w=1200&h=800&fit=crop",
    rating: 4.5,
    bestTime: "Junio - Septiembre",
    avgFlightPrice: "110€",
    readTime: "6 min",
    keywords: ["hoteles en Burdeos", "dónde dormir en Burdeos", "hoteles Burdeos centro"],
    transport: "Tranvía eficiente (3 líneas) y autobuses. Aeropuerto conecta por tranvía (línea A + autobús). Tren TGV a París en 2h. El centro es fácil de recorrer a pie.",
    travelTips: ["La Cité du Vin es imprescindible para los amantes del vino", "El Espejo de Agua es el lugar más fotogénico al atardecer", "Saint-Émilion está a 40min en tren y merece la visita", "Los canelés son el postre típico, pruébalos en La Toque Cuivrée"],
    neighborhoods: [
      { name: "Saint-Pierre", desc: "El barrio histórico con calles peatonales, restaurantes y el Espejo de Agua." },
      { name: "Chartrons", desc: "Barrio de anticuarios, galerías de arte y boutiques vintage." },
      { name: "Saint-Michel", desc: "Barrio multicultural con el mercado más grande de Burdeos los fines de semana." },
    ],
    dayTrips: ["Saint-Émilion - Pueblo medieval y bodegas a 40min", "Dune du Pilat - La duna más grande de Europa a 1h"],
    budget: "Económico: 70€/día. Medio: 140€/día. Lujo: 300€+/día.",
  },

  // ── Italia ──
  {
    type: "country",
    name: "Italia",
    slug: "italia",
    country: "Italia",
    countrySlug: "italia",
    continent: "Europa",
    continentSlug: "europa",
    short: "Historia milenaria, pasta, vino y el mejor arte del mundo.",
    description: "Italia es un museo al aire libre. Desde el Coliseo romano hasta los canales de Venecia, pasando por la cúpula de Brunelleschi en Florencia y la costa de Amalfi, Italia enamora con su cultura, gastronomía y paisajes.",
    whatToSee: ["Coliseo y Foro Romano", "Canales de Venecia", "Duomo de Florencia", "Costa de Amalfi"],
    gastronomy: ["Pasta fresca y pizza napolitana", "Gelato artesanal", "Vinos Chianti y Barolo", "Espresso italiano"],
    activities: ["Tour histórico en Roma", "Paseo en góndola", "Ruta del vino en Toscana", "Clase de cocina italiana"],
    priceRange: "70€ - 200€",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&h=800&fit=crop",
    badge: "Cultural",
    rating: 4.8,
    bestTime: "Abril - Octubre",
    avgFlightPrice: "100€",
    readTime: "12 min",
    keywords: ["hoteles en Italia", "viajar a Italia", "destinos Italia", "vacaciones Italia"],
    cities: ["roma", "milan", "venecia", "florencia", "napoles"],
  },
  {
    type: "city",
    name: "Roma",
    slug: "roma",
    country: "Italia",
    countrySlug: "italia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "italia",
    short: "La Ciudad Eterna con 3000 años de historia a cada paso.",
    description: "Roma, la Ciudad Eterna, es un museo al aire libre donde cada calle cuenta siglos de historia. Desde el Coliseo Romano hasta el Vaticano, ofrece experiencias únicas que combinan arte antiguo y gastronomía mediterránea.",
    whatToSee: ["Coliseo y Foro Romano", "Ciudad del Vaticano y Capilla Sixtina", "Fontana di Trevi y Pantheon", "Plaza de España y Trastevere"],
    gastronomy: ["Pasta fresca y carbonara auténtica", "Pizza romana al taglio", "Gelato artesanal", "Supplì y fritti romanos"],
    activities: ["Visitar Vatican Museums con guía", "Clase de cocina italiana", "Tour de barrios históricos", "Paseo en Vespa"],
    priceRange: "70€ - 180€",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&h=800&fit=crop",
    badge: "Cultural",
    rating: 4.7,
    bestTime: "Marzo - Mayo",
    avgFlightPrice: "120€",
    readTime: "8 min",
    keywords: ["hoteles en Roma", "dónde dormir en Roma", "hoteles cerca del Coliseo", "hoteles Roma centro"],
    transport: "Metro (3 líneas A, B, C) cubre lo principal. Autobuses y tranvías ATAC. El Roma Pass incluye transporte y museos. Aeropuerto Fiumicino conecta por tren Leonardo Express (14€).",
    travelTips: ["La Fontana di Trevi es más espectacular al amanecer sin gente", "El Coliseo merece la pena con visita guiada subterránea", "El Vaticano tiene entrada gratuita el último domingo de mes", "Los restaurantes cerca de monumentos son más caros, busca en calles laterales", "El gelato artesanal se reconoce porque no tiene colores fluorescentes"],
    neighborhoods: [
      { name: "Trastevere", desc: "Barrio bohemio con calles empedradas, restaurantes auténticos y vida nocturna." },
      { name: "Monti", desc: "Barrio hipster cerca del Coliseo con tiendas vintage y bares cool." },
      { name: "Centro Storico", desc: "El corazón de Roma con la Fontana di Trevi, Panteón y Plaza Navona." },
      { name: "Prati", desc: "Zona elegante cerca del Vaticano, más tranquila y con buenos restaurantes." },
    ],
    dayTrips: ["Pompeya - Ruinas romanas a 1h en tren", "Tívoli - Villa d'Este y sus fuentes a 45min"],
    budget: "Económico: 75€/día. Medio: 150€/día. Lujo: 350€+/día.",
  },
  {
    type: "city",
    name: "Milán",
    slug: "milan",
    country: "Italia",
    countrySlug: "italia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "italia",
    short: "Capital de la moda mundial con el Duomo como joya.",
    description: "Milán es la capital de la moda y el diseño. Su imponente Duomo gótico, la última cena de Da Vinci y los elegantes cafés de la Galleria Vittorio Emanuele II crean una atmósfera sofisticada y cosmopolita.",
    whatToSee: ["Duomo de Milán y Piazza del Duomo", "La Última Cena de Da Vinci", "Galleria Vittorio Emanuele II", "Castello Sforzesco y Barrio Brera"],
    gastronomy: ["Risotto alla milanese", "Cotoletta alla milanese", "Panettone y aperitivo", "Café en la Galleria"],
    activities: ["Shopping en Quadrilatero d'Oro", "Ópera en La Scala", "Tour de diseño en Zona Tortona", "Excursión a los Lagos"],
    priceRange: "80€ - 200€",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=800&fit=crop",
    rating: 4.5,
    bestTime: "Abril - Septiembre",
    avgFlightPrice: "90€",
    readTime: "7 min",
    keywords: ["hoteles en Milán", "dónde dormir en Milán", "hoteles Milán centro", "hoteles baratos Milán"],
    transport: "Metro (5 líneas) eficiente. Tranvía histórico es icónico. Aeropuerto Malpensa conecta por tren Malpensa Express (50min, 13€). Trenes regionales a toda Italia.",
    travelTips: ["La Última Cena de Da Vinci requiere reserva con meses de antelación", "El Duomo se puede subir a las terrazas andando o en ascensor", "El barrio Brera es perfecto para cenar, lleno de restaurantes elegantes", "La Semana de la Moda (febrero y septiembre) dispara los precios de hotel"],
    neighborhoods: [
      { name: "Brera", desc: "Barrio bohemio con galerías de arte, restaurantes elegantes y calles adoquinadas." },
      { name: "Navigli", desc: "Zona de canales con bares, restaurantes y vida nocturna vibrante." },
      { name: "Centro", desc: "Duomo, Galleria Vittorio Emanuele y el quadrato della moda." },
    ],
    dayTrips: ["Lago di Como - Pueblos románticos a 1h en tren", "Lago Maggiore - Islas Borromeas a 1.5h"],
    budget: "Económico: 80€/día. Medio: 160€/día. Lujo: 380€+/día.",
  },
  {
    type: "city",
    name: "Venecia",
    slug: "venecia",
    country: "Italia",
    countrySlug: "italia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "italia",
    short: "La ciudad flotante más romántica del mundo.",
    description: "Venecia es única en el mundo. Sus canales en lugar de calles, sus góndolas, la Plaza de San Marcos y el Puente de Rialto crean una atmósfera mágica que parece suspendida en el tiempo.",
    whatToSee: ["Plaza de San Marcos y Basílica", "Palacio Ducal y Puente de los Suspiros", "Gran Canal y Puente de Rialto", "Isla de Murano y Burano"],
    gastronomy: ["Cicchetti venecianos", "Risotto de mariscos", "Fritto misto y sardine in saor", "Tiramisú y zabaglione"],
    activities: ["Paseo en góndola por los canales", "Visita a las islas", "Museo Peggy Guggenheim", "Carnaval de Venecia"],
    priceRange: "90€ - 220€",
    image: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=1200&h=800&fit=crop",
    badge: "Romántico",
    rating: 4.7,
    bestTime: "Abril - Junio",
    avgFlightPrice: "110€",
    readTime: "7 min",
    keywords: ["hoteles en Venecia", "dónde dormir en Venecia", "hoteles románticos Venecia", "hoteles Venecia centro"],
    transport: "Vaporetto (autobús acuático) es el transporte principal. El Actv Tourist Pass por 1-7 días es la mejor opción. Desde el aeropuerto, water taxi (110€) o Alilaguna (15€).",
    travelTips: ["Visita la Plaza de San Marcos al amanecer para verla vacía", "El paseo en góndola oficial son 80€ por 30 minutos, negocia antes", "Los restaurantes con vistas al canal son carísimos, come en callejones", "Murano y Burano merecen medio día cada una", "Carnaval en febrero es espectacular pero hoteles se triplican"],
    neighborhoods: [
      { name: "San Marco", desc: "El corazón turístico con la Plaza, la Basílica y el Palacio Ducal." },
      { name: "Dorsoduro", desc: "Barrio universitario con galerías, bares locales y ambiente auténtico." },
      { name: "Cannaregio", desc: "Barrio residencial con el gueto judío, menos turístico y más auténtico." },
    ],
    dayTrips: ["Murano y Burano - Islas del vidrio y el encaje", "Padua - Ciudad universitaria y Capilla Scrovegni a 30min"],
    budget: "Económico: 85€/día. Medio: 170€/día. Lujo: 400€+/día.",
  },
  {
    type: "city",
    name: "Florencia",
    slug: "florencia",
    country: "Italia",
    countrySlug: "italia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "italia",
    short: "Cuna del Renacimiento con el arte de Miguel Ángel y Da Vinci.",
    description: "Florencia es la cuna del Renacimiento. La cúpula de Brunelleschi, el David de Miguel Ángel en la Accademia, el Ponte Vecchio y los jardines de Boboli convierten a esta ciudad en un museo viviente.",
    whatToSee: ["Duomo y Campanile de Giotto", "Galería Uffizi", "Ponte Vecchio y Palazzo Vecchio", "Jardines de Boboli"],
    gastronomy: ["Bistecca alla fiorentina", "Pappa al pomodoro", "Vinos Chianti", "Gelato artesanal en Piazza del Duomo"],
    activities: ["Tour renacentista", "Atardecer en Piazzale Michelangelo", "Clase de cocina toscana", "Excursión a la Toscana"],
    priceRange: "75€ - 180€",
    image: "https://images.unsplash.com/photo-1543429257-3eb0b65d9c58?w=1200&h=800&fit=crop",
    rating: 4.7,
    bestTime: "Abril - Junio",
    avgFlightPrice: "100€",
    readTime: "7 min",
    keywords: ["hoteles en Florencia", "dónde dormir en Florencia", "hoteles Florencia centro", "hoteles baratos Florencia"],
    transport: "Florencia es compacta, se recorre andando. Autobuses urbanos (ATAF). Aeropuerto conecta por tranvía (T2) en 20min. Tren a Roma en 1.5h, a Venecia en 2h.",
    travelTips: ["La Galería Uffizi requiere reserva online con 1-2 semanas", "Piazzale Michelangelo al atardecer tiene las mejores vistas", "El David de Miguel Ángel está en la Accademia, no en los Uffizi", "El mercado de San Lorenzo es ideal para comprar cuero", "La Toscana merece una excursión de día completo"],
    neighborhoods: [
      { name: "Centro Storico", desc: "El Duomo, la Piazza della Signoria y el Ponte Vecchio en una zona peatonal." },
      { name: "Oltrarno", desc: "Al otro lado del río, con talleres artesanales, bares y el Palacio Pitti." },
      { name: "San Lorenzo", desc: "Zona del mercado central y la basílica de los Medici." },
    ],
    dayTrips: ["Siena - Ciudad medieval a 1h", "San Gimignano - Torre medieval a 1.5h", "Chianti - Ruta del vino a 30min"],
    budget: "Económico: 75€/día. Medio: 150€/día. Lujo: 350€+/día.",
  },
  {
    type: "city",
    name: "Nápoles",
    slug: "napoles",
    country: "Italia",
    countrySlug: "italia",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "italia",
    short: "Pizza, historia y el Vesubio vigilando la bahía.",
    description: "Nápoles es una ciudad visceral y auténtica. Cuna de la pizza, con el Vesubio de fondo y Pompeya a las puertas, ofrece una experiencia italiana sin filtros, entre el caos y la belleza más pura.",
    whatToSee: ["Centro histórico y Spaccanapoli", "Castel dell'Ovo y Castel Nuovo", "Pompeya y Herculano", "Museo Arqueológico Nacional"],
    gastronomy: ["Pizza napolitana auténtica", "Pastiera y sfogliatella", "Mozzarella di bufala", "Limoncello y espresso"],
    activities: ["Visita a Pompeya", "Excursión a la Costa Amalfitana", "Paseo por el Lungomare", "Cata de pizza en Antica Pizzeria"],
    priceRange: "50€ - 120€",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&h=800&fit=crop",
    rating: 4.5,
    bestTime: "Abril - Junio",
    avgFlightPrice: "80€",
    readTime: "6 min",
    keywords: ["hoteles en Nápoles", "dónde dormir en Nápoles", "hoteles centro Nápoles"],
    transport: "Metro (2 líneas) y funiculares. El aeropuerto conecta por Alibus (5€). Trenes a Pompeya (30min) y Costa Amalfitana. El centro es caótico pero se anda bien.",
    travelTips: ["La pizza napolitana auténtica se come en Antica Pizzeria Da Michele", "Pompeya requiere medio día completo, lleva agua y sombrero", "El metro de Nápoles tiene algunas de las estaciones más bonitas del mundo (Toledo)", "Los barrios españoles son vibrantes pero ten cuidado con objetos de valor"],
    neighborhoods: [
      { name: "Centro Storico", desc: "Patrimonio de la Humanidad con Spaccanapoli, iglesias y mercados callejeros." },
      { name: "Chiaia", desc: "Zona elegante con tiendas de diseño, restaurantes y el paseo marítimo." },
      { name: "Vomero", desc: "Barrio residencial en la colina con vistas espectaculares al Vesubio." },
    ],
    dayTrips: ["Pompeya y Herculano - Ruinas romanas a 30min", "Costa Amalfitana - Positano y Amalfi a 1.5h"],
    budget: "Económico: 55€/día. Medio: 110€/día. Lujo: 250€+/día.",
  },

  // ── Reino Unido ──
  {
    type: "country",
    name: "Reino Unido",
    slug: "reino-unido",
    country: "Reino Unido",
    countrySlug: "reino-unido",
    continent: "Europa",
    continentSlug: "europa",
    short: "Historia real, cultura global y paisajes que inspiran.",
    description: "Reino Unido ofrece desde la energía de Londres hasta los paisajes de Escocia. Museos gratuitos, teatros del West End, pubs tradicionales y castillos medievales se combinan en este destino fascinante.",
    whatToSee: ["Big Ben y Houses of Parliament", "Torre de Londres", "Castillos de Edimburgo y Windsor", "Stonehenge y Bath"],
    gastronomy: ["Fish and chips con mushy peas", "Afternoon tea", "Sunday roast", "Cervezas y ales británicas"],
    activities: ["Musical en West End", "Tour por los pubs históricos", "Excursión a Stonehenge", "Visita a los Cotswolds"],
    priceRange: "80€ - 280€",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "120€",
    readTime: "10 min",
    keywords: ["hoteles en Reino Unido", "viajar a Reino Unido", "destinos Reino Unido"],
    cities: ["londres", "edimburgo"],
  },
  {
    type: "city",
    name: "Londres",
    slug: "londres",
    country: "Reino Unido",
    countrySlug: "reino-unido",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "reino-unido",
    short: "Capital global con museos gratuitos, teatro y parques reales.",
    description: "Londres combina historia milenaria con modernidad vibrante. Desde el Big Ben hasta Buckingham Palace, pasando por el Tower Bridge y el British Museum, ofrece una experiencia cultural sin igual.",
    whatToSee: ["Big Ben y Houses of Parliament", "Buckingham Palace y Westminster", "Tower Bridge y Tower of London", "British Museum y National Gallery"],
    gastronomy: ["Fish and chips tradicional", "Afternoon tea en The Ritz", "Mercados de Borough y Brick Lane", "Pubs históricos y gastropubs"],
    activities: ["Musical en West End", "Walking tour por los barrios", "Crucero por el Támesis", "Cambio de guardia real"],
    priceRange: "120€ - 280€",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=800&fit=crop",
    rating: 4.7,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "130€",
    readTime: "9 min",
    keywords: ["hoteles en Londres", "dónde dormir en Londres", "hoteles baratos Londres", "hoteles centro Londres"],
    transport: "Metro (Tube, 11 líneas) es el más antiguo del mundo. Oyster Card es la mejor opción. Autobuses rojos de dos pisos icónicos. Aeropuertos: Heathrow (Heathrow Express 15min), Gatwick, Stansted.",
    travelTips: ["Los museos nacionales son gratuitos (British Museum, National Gallery, Tate Modern)", "El Tube cierra sobre medianoche, los fines de semana hay servicio nocturno", "Compra Oyster Card en vez de billetes sueltos, ahorras 50%", "Los mercados de Borough, Camden y Brick Lane son imprescindibles", "El cambio de guardia en Buckingham Palace es a las 11:00h"],
    neighborhoods: [
      { name: "Covent Garden", desc: "Corazón turístico con el mercado, teatros, restaurantes y artistas callejeros." },
      { name: "Shoreditch", desc: "Barrio hipster con arte urbano, mercadillos vintage y los mejores bares." },
      { name: "South Kensington", desc: "Zona de museos, tiendas de lujo y el precioso Hyde Park." },
      { name: "Camden Town", desc: "Barrio alternativo con el famoso mercado, música en vivo y ambiente ecléctico." },
    ],
    dayTrips: ["Windsor - Castillo real a 45min en tren", "Oxford - Universidad histórica a 1h"],
    budget: "Económico: 90€/día. Medio: 180€/día. Lujo: 400€+/día.",
  },
  {
    type: "city",
    name: "Edimburgo",
    slug: "edimburgo",
    country: "Reino Unido",
    countrySlug: "reino-unido",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "reino-unido",
    short: "Castillos, whisky y el festival más famoso del mundo.",
    description: "Edimburgo es la joya de Escocia. Su castillo medieval domina la ciudad, el casco antiguo con calles empedradas y el festival de Edimburgo en agosto atraen visitantes de todo el mundo.",
    whatToSee: ["Castillo de Edimburgo", "Royal Mile y Holyrood Palace", "Arthur's Seat y Calton Hill", "Museo Nacional de Escocia"],
    gastronomy: ["Haggis, neeps and tatties", "Whisky escocés", "Cullen skink y salmon", "Shortbread y tablet"],
    activities: ["Tour de whisky", "Festival Fringe en agosto", "Excursión a Highlands", "Fantasma tour por Old Town"],
    priceRange: "80€ - 180€",
    image: "https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Mayo - Agosto",
    avgFlightPrice: "110€",
    readTime: "7 min",
    keywords: ["hoteles en Edimburgo", "dónde dormir en Edimburgo", "hoteles Edimburgo centro"],
    transport: "Tranvía conecta aeropuerto con centro (35min). Autobuses Lothian cubren la ciudad. Edimburgo se divide en Old Town y New Town, ambas walkable.",
    travelTips: ["El Festival Fringe en agosto es el más grande del mundo, reserva con meses", "Arthur's Seat tiene las mejores vistas de la ciudad, subida de 45min", "El Scotch Whisky Experience es una buena introducción al whisky escocés", "El Castillo de Edimburgo dispara coñón a las 13:00h cada día"],
    neighborhoods: [
      { name: "Old Town", desc: "Casco medieval con la Royal Mile, el Castillo y calles empedradas." },
      { name: "New Town", desc: "Georgiana y elegante, con Princes Street y tiendas de lujo." },
      { name: "Stockbridge", desc: "Barrio residencial con mercados de fin de semana y ambiente local." },
    ],
    dayTrips: ["Highlands - Paisajes escoceses a 1.5h", "Loch Lomond - Lago y parque natural a 1h"],
    budget: "Económico: 75€/día. Medio: 150€/día. Lujo: 320€+/día.",
  },

  // ── Países Bajos ──
  {
    type: "country",
    name: "Países Bajos",
    slug: "paises-bajos",
    country: "Países Bajos",
    countrySlug: "paises-bajos",
    continent: "Europa",
    continentSlug: "europa",
    short: "Canales, molinos y tulipanes en el país más feliz de Europa.",
    description: "Países Bajos es mucho más que Ámsterdam. Sus ciudades con canales, molinos de viento, campos de tulipanes y una cultura ciclista única lo convierten en un destino fascinante para explorar.",
    whatToSee: ["Canales de Ámsterdam", "Molinos de Kinderdijk", "Campos de tulipanes Keukenhof", "Museo Van Gogh y Rijksmuseum"],
    gastronomy: ["Poffertjes y stroopwafels", "Queso Gouda y Edam", "Haring crudo con cebolla", "Bitterballen y kroket"],
    activities: ["Paseo en bicicleta", "Crucero por los canales", "Visita los mercados de quesos", "Tour de diseño"],
    priceRange: "70€ - 180€",
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&h=800&fit=crop",
    rating: 4.5,
    bestTime: "Abril - Septiembre",
    avgFlightPrice: "90€",
    readTime: "10 min",
    keywords: ["hoteles en Países Bajos", "viajar a Países Bajos", "destinos Países Bajos"],
    cities: ["amsterdam", "roterdam"],
  },
  {
    type: "city",
    name: "Ámsterdam",
    slug: "amsterdam",
    country: "Países Bajos",
    countrySlug: "paises-bajos",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "paises-bajos",
    short: "Canales, museos de clase mundial y una atmósfera única.",
    description: "Ámsterdam cautiva con sus icónicos canales del siglo XVII, arquitectura narrow houses y una escena cultural vibrante. Ofrece desde los maestros del Rijksmuseum hasta el Barrio Jordaan.",
    whatToSee: ["Rijksmuseum y Van Gogh Museum", "Casa de Ana Frank", "Canales y Jordaan", "Mercado de las Flores"],
    gastronomy: ["Poffertjes y stroopwafels", "Queso holandés", "Haring crudo", "Cerveza artesanal"],
    activities: ["Crucero por los canales", "Alquilar bicicleta", "Tour de diseño", "Mercado Albert Cuyp"],
    priceRange: "100€ - 200€",
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&h=800&fit=crop",
    rating: 4.5,
    bestTime: "Abril - Septiembre",
    avgFlightPrice: "100€",
    readTime: "7 min",
    keywords: ["hoteles en Ámsterdam", "dónde dormir en Ámsterdam", "hoteles baratos Ámsterdam"],
    transport: "Tranvías y metro (GVB). Bicicleta es el rey, alquila una. Tren desde Schiphol cada 15min. Los canales se navegan en barco turístico. Pase I Amsterdam incluye museos y transporte.",
    travelTips: ["Los museos principales (Rijksmuseum, Van Gogh) requieren reserva online", "El Barrio Rojo no permite fotos, respeta las normas", "Los canales al atardecer desde el Puente de los Siete Puntos son espectaculares", "Los coffee shops son legales pero solo para mayores de 18", "Los mercados Albert Cuyp y Ten Katemarkt son ideales para probar comida local"],
    neighborhoods: [
      { name: "Centro", desc: "Dam Square, Barrio Rojo y los grandes almacenes en una zona peatonal." },
      { name: "Jordaan", desc: "Barrio bohemio con galerías, boutiques, mercados y bares locales." },
      { name: "De Pijp", desc: "Barrio multicultural con el mercado Albert Cuyp y restaurantes étnicos." },
    ],
    dayTrips: ["Zaanse Schans - Molinos y quesos a 20min", "Keukenhof - Campos de tulipanes (solo marzo-mayo)"],
    budget: "Económico: 85€/día. Medio: 170€/día. Lujo: 380€+/día.",
  },
  {
    type: "city",
    name: "Róterdam",
    slug: "roterdam",
    country: "Países Bajos",
    countrySlug: "paises-bajos",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "paises-bajos",
    short: "Arquitectura vanguardista y el mayor puerto de Europa.",
    description: "Róterdam es la ciudad de la arquitectura moderna. Bombardeada en la Segunda Guerra Mundial, se reinventó con edificios icónicos como las Casas Cubo, el Markthal y el Erasmusbrug, creando un skyline único en Europa.",
    whatToSee: ["Casas Cubo y Markthal", "Erasmusbrug y puerto", "Museo Boijmans Van Beuningen", "Torre Euromast"],
    gastronomy: ["Market Hall gastronómico", "Frikandel y bitterballen", "Cerveza artesanal local", "Comida internacional"],
    activities: ["Tour arquitectónico", "Paseo en barco por el puerto", "Museo Marítimo", "Día de playa en Hoek van Holland"],
    priceRange: "70€ - 150€",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&h=800&fit=crop",
    rating: 4.3,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "90€",
    readTime: "5 min",
    keywords: ["hoteles en Róterdam", "dónde dormir en Róterdam", "hoteles Róterdam centro"],
  },

  // ── Alemania ──
  {
    type: "country",
    name: "Alemania",
    slug: "alemania",
    country: "Alemania",
    countrySlug: "alemania",
    continent: "Europa",
    continentSlug: "europa",
    short: "Historia, cerveza y paisajes de cuento de hadas.",
    description: "Alemania ofrece desde la historia del Muro de Berlín hasta los castillos de Baviera. Sus mercados navideños, la Ruta Romántica y una cultura cervecera centenaria la convierten en un destino fascinante.",
    whatToSee: ["Puerta de Brandenburgo", "Castillo de Neuschwanstein", "Catedral de Colonia", "Muro de Berlín y East Side Gallery"],
    gastronomy: ["Salchichas y currywurst", "Schnitzel vienés", "Cerveza alemana", "Pretzels y strudel"],
    activities: ["Ruta Romántica", "Oktoberfest en Múnich", "Tour de castillos bávaros", "Mercados navideños"],
    priceRange: "60€ - 150€",
    image: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "80€",
    readTime: "10 min",
    keywords: ["hoteles en Alemania", "viajar a Alemania", "destinos Alemania"],
    cities: ["berlin", "munich", "hamburgo"],
  },
  {
    type: "city",
    name: "Berlín",
    slug: "berlin",
    country: "Alemania",
    countrySlug: "alemania",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "alemania",
    short: "Historia viva, arte underground y la mejor vida nocturna.",
    description: "Berlín es una metrópolis en constante transformación. Desde el Muro de Berlín hasta la isla de los Museos, la ciudad cuenta historias de división y reunificación con una escena artística vibrante.",
    whatToSee: ["Brandenburger Tor y Reichstag", "East Side Gallery y Muro", "Museumsinsel", "Checkpoint Charlie"],
    gastronomy: ["Currywurst y Döner", "Berliner Weisse", "Cerveza artesanal", "Comida turca en Kreuzberg"],
    activities: ["Visitar memorial del Muro", "Party en Berghain", "Tour de Street Art", "Mercado de Mauerpark"],
    priceRange: "70€ - 150€",
    image: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=1200&h=800&fit=crop",
    badge: "Emergente",
    rating: 4.5,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "85€",
    readTime: "7 min",
    keywords: ["hoteles en Berlín", "dónde dormir en Berlín", "hoteles baratos Berlín"],
    transport: "Metro (U-Bahn, 9 líneas), tren ligero (S-Bahn) y autobuses. Berlin WelcomeCard incluye transporte y descuentos. Aeropuerto BER conecta por tren FEX en 30min.",
    travelTips: ["La East Side Gallery es el fragmento más largo del Muro, gratis", "El Reichstag tiene cúpula gratis pero requiere reserva online", "Berlín es muy económico comparado con otras capitales europeas", "Los museos en la Isla de los Museos merecen 2 días completos", "El mercadillo de Mauerpark los domingos es una experiencia única"],
    neighborhoods: [
      { name: "Mitte", desc: "El centro histórico con la Puerta de Brandenburgo, Reichstag y la Isla de los Museos." },
      { name: "Kreuzberg", desc: "Barrio alternativo con arte callejero, bares, kebab y vida nocturna." },
      { name: "Prenzlauer Berg", desc: "Barrio familiar con calles arboladas, cafés y mercados de agricultores." },
    ],
    dayTrips: ["Potsdam - Palacios Sanssouci a 30min en tren", "Spreewald - Bosque y canales a 1.5h"],
    budget: "Económico: 55€/día. Medio: 110€/día. Lujo: 250€+/día.",
  },
  {
    type: "city",
    name: "Múnich",
    slug: "munich",
    country: "Alemania",
    countrySlug: "alemania",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "alemania",
    short: "Cerveza, cultura bávara y los Alpes a las puertas.",
    description: "Múnich es la capital de Baviera y la cuna del Oktoberfest. Sus jardines de cerveza, el centro histórico con el Marienplatz y la cercanía a los Alpes la convierten en un destino que combina tradición y naturaleza.",
    whatToSee: ["Marienplatz y Glockenspiel", "Oktoberfest en Theresienwiese", "Palacio de Nymphenburg", "Jardín Inglés y Eisbach"],
    gastronomy: ["Weisswurst y pretzel", "Cerveza en Hofbräuhaus", "Schweinshaxe y Knödel", "Apfelstrudel"],
    activities: ["Oktoberfest (sept-oct)", "Excursión a Neuschwanstein", "Tour de cerveza bávara", "Esquí en los Alpes"],
    priceRange: "80€ - 180€",
    image: "https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?w=1200&h=800&fit=crop",
    badge: "Oktoberfest",
    rating: 4.6,
    bestTime: "Mayo - Octubre",
    avgFlightPrice: "80€",
    readTime: "7 min",
    keywords: ["hoteles en Múnich", "dónde dormir en Múnich", "hoteles Múnich centro"],
  },
  {
    type: "city",
    name: "Hamburgo",
    slug: "hamburgo",
    country: "Alemania",
    countrySlug: "alemania",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "alemania",
    short: "Puerto, arquitectura moderna y la vida cultural del norte.",
    description: "Hamburgo es la segunda ciudad de Alemania y uno de los puertos más grandes de Europa. Su Elbphilharmonie, el barrio de St. Pauli con el legendario Reeperbahn y sus canales la convierten en un destino único.",
    whatToSee: ["Elbphilharmonie y puerto", "Speicherstadt y HafenCity", "St. Pauli y Reeperbahn", "Iglesia de San Miguel"],
    gastronomy: ["Fischbrötchen y arenque", "Franzbrötchen", "Cerveza Astra", "Comida internacional en el puerto"],
    activities: ["Tour por el puerto", "Concierto en Elbphilharmonie", "Noche en Reeperbahn", "Paseo por Speicherstadt"],
    priceRange: "70€ - 160€",
    image: "https://images.unsplash.com/photo-1559511260-66a68e2a7ed0?w=1200&h=800&fit=crop",
    rating: 4.4,
    bestTime: "Mayo - Septiembre",
    avgFlightPrice: "85€",
    readTime: "6 min",
    keywords: ["hoteles en Hamburgo", "dónde dormir en Hamburgo", "hoteles Hamburgo centro"],
  },

  // ── Austria ──
  {
    type: "city",
    name: "Viena",
    slug: "viena",
    country: "Austria",
    countrySlug: "austria",
    continent: "Europa",
    continentSlug: "europa",
    short: "Música, palacios imperiales y la cultura del café vienés.",
    description: "Viena es la capital del vals y la música clásica. Sus palacios imperiales como Schönbrunn y Hofburg, sus cafés históricos y su escena musical hacen de la ciudad una experiencia única.",
    whatToSee: ["Palacio de Schönbrunn y Hofburg", "Ópera Estatal y Musikverein", "Belvedere y jardines", "Naschmarkt y Secession"],
    gastronomy: ["Café vienés y Sachertorte", "Wiener Schnitzel", "Apfelstrudel", "Wiener Melange"],
    activities: ["Concierto de Mozart", "Tour de cafés imperiales", "Degustación de vinos", "Spa en Therme"],
    priceRange: "90€ - 180€",
    image: "https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Abril - Octubre",
    avgFlightPrice: "110€",
    readTime: "7 min",
    keywords: ["hoteles en Viena", "dónde dormir en Viena", "hoteles baratos Viena"],
  },

  // ── Chequia ──
  {
    type: "city",
    name: "Praga",
    slug: "praga",
    country: "Chequia",
    countrySlug: "chequia",
    continent: "Europa",
    continentSlug: "europa",
    short: "Ciudad de las cien torres con arquitectura gótica y precios asequibles.",
    description: "Praga, la Ciudad de las Cien Torres, parece sacada de un cuento medieval. Su Ciudad Vieja con el Reloj Astronómico, el Puente Carlos y el Castillo de Praga ofrecen una experiencia visual inolvidable.",
    whatToSee: ["Castillo de Praga", "Puente Carlos y Ciudad Vieja", "Reloj Astronómico", "Casa Danzante y Petřín"],
    gastronomy: ["Cerveza Pilsner Urquell", "Svíčková y guláš", "Trdelník", "Colinabo y knedlíky"],
    activities: ["Tour de cerveza artesanal", "Paseo por Petřín hill", "Concierto de música clásica", "Excursión a Český Krumlov"],
    priceRange: "50€ - 120€",
    image: "https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200&h=800&fit=crop",
    badge: "Mejor Precio",
    rating: 4.5,
    bestTime: "Abril - Junio",
    avgFlightPrice: "70€",
    readTime: "6 min",
    keywords: ["hoteles en Praga", "dónde dormir en Praga", "hoteles baratos Praga"],
  },

  // ── Portugal ──
  {
    type: "country",
    name: "Portugal",
    slug: "portugal",
    country: "Portugal",
    countrySlug: "portugal",
    continent: "Europa",
    continentSlug: "europa",
    short: "Costas doradas, fado y la mejor gastronomía atlántica.",
    description: "Portugal enamora con sus ciudades históricas, playas doradas del Algarve y una gastronomía de primer nivel. Lisboa y Oporto compiten en encanto con sus colinas, vinos y el fado más conmovedor.",
    whatToSee: ["Torre de Belém", "Palacio da Pena en Sintra", "Ribeira de Oporto", "Playas del Algarve"],
    gastronomy: ["Pastéis de nata", "Bacalao a brás", "Vino de Oporto", "Francesinha"],
    activities: ["Ruta del fado en Lisboa", "Cata de vinos en Oporto", "Surf en el Algarve", "Visita a Sintra"],
    priceRange: "50€ - 140€",
    image: "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Marzo - Octubre",
    avgFlightPrice: "60€",
    readTime: "10 min",
    keywords: ["hoteles en Portugal", "viajar a Portugal", "destinos Portugal"],
    cities: ["lisboa", "oporto", "faro"],
  },
  {
    type: "city",
    name: "Lisboa",
    slug: "lisboa",
    country: "Portugal",
    countrySlug: "portugal",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "portugal",
    short: "Colinas, fado y pastéis de nata en la capital atlántica.",
    description: "Lisboa enamora con sus calles empedradas, tranvías amarillos, el fado en Alfama y los pastéis de nata de Belém. Construida sobre siete colinas, ofrece vistas panorámicas desde miradores únicos.",
    whatToSee: ["Castillo de São Jorge y Alfama", "Belém y Torre de Belém", "Praça do Comércio", "Tranvía 28 y Barrio Alto"],
    gastronomy: ["Pastéis de Belém", "Bacalao a brás", "Ginjinha", "Francesinha"],
    activities: ["Paseo en tranvía 28", "Atardecer en Miradouro", "Noche de Fado", "Excursión a Sintra"],
    priceRange: "60€ - 140€",
    image: "https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Marzo - Octubre",
    avgFlightPrice: "75€",
    readTime: "7 min",
    keywords: ["hoteles en Lisboa", "dónde dormir en Lisboa", "hoteles baratos Lisboa"],
    transport: "Metro (4 líneas), tranvías históricos (el 28 es icónico) y funiculares. Aeropuerto conecta por metro (línea vermelha) en 20min. Lisboa es muy cuesta arriba, usa el metro.",
    travelTips: ["El tranvía 28 es el más pintoresco pero siempre lleno, súbete en la primera parada", "Los pastéis de nata auténticos son en Pastéis de Belém", "El fado se escucha mejor en Alfama, en casas de fado tradicionales", "La tarjeta Lisboa Card incluye transporte y museos", "Las vistas desde el Castillo de São Jorge al atardecer son imprescindibles"],
    neighborhoods: [
      { name: "Alfama", desc: "El barrio más antiguo con calles estrechas, fado y miradores." },
      { name: "Baixa-Chiado", desc: "El centro reconstruido tras el terremoto, con tiendas y restaurantes." },
      { name: "Bairro Alto", desc: "Barrio bohemio y de fiesta, con bares, galerías y miradores." },
    ],
    dayTrips: ["Sintra - Palacio da Pena y castillo a 40min", "Cascais - Pueblo costero a 30min"],
    budget: "Económico: 55€/día. Medio: 110€/día. Lujo: 240€+/día.",
  },
  {
    type: "city",
    name: "Oporto",
    slug: "oporto",
    country: "Portugal",
    countrySlug: "portugal",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "portugal",
    short: "Vino, puente y el Duero en la ciudad más auténtica de Portugal.",
    description: "Oporto es la ciudad del vino que le da nombre. Su casco histórico, las bodegas de Vila Nova de Gaia, el puente Dom Luís I y la Ribeira crean una atmósfera mágica a orillas del Duero.",
    whatToSee: ["Ribeira y Puente Dom Luís I", "Bodegas de Vila Nova de Gaia", "Torre de los Clérigos", "Estación de São Bento"],
    gastronomy: ["Vino de Oporto", "Francesinha", "Bacalhau à Gomes de Sá", "Pastéis de chaves"],
    activities: ["Cata de vino de Oporto", "Crucero por el Duero", "Visita al valle del Duero", "Tour del azulejo"],
    priceRange: "50€ - 120€",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Abril - Octubre",
    avgFlightPrice: "60€",
    readTime: "6 min",
    keywords: ["hoteles en Oporto", "dónde dormir en Oporto", "hoteles baratos Oporto"],
  },
  {
    type: "city",
    name: "Faro",
    slug: "faro",
    country: "Portugal",
    countrySlug: "portugal",
    continent: "Europa",
    continentSlug: "europa",
    parentSlug: "portugal",
    short: "Puerta al Algarve con playas doradas y acantilados.",
    description: "Faro es la capital del Algarve y la puerta de entrada a las playas más espectaculares de Portugal. Sus acantilados dorados, grutas marinas y la Ria Formosa crean un paraíso natural único.",
    whatToSee: ["Ria Formosa y las islas-barriera", "Casco histórico de Faro", "Grutas de Benagil", "Playa da Marinha"],
    gastronomy: ["Pescado a la parrilla", "Cataplana de mariscos", "Pastéis de almonda", "Vinos del Algarve"],
    activities: ["Excursión a las grutas marinas", "Día de playa en islas-barriera", "Observación de aves", "Golf en el Algarve"],
    priceRange: "50€ - 130€",
    image: "https://images.unsplash.com/photo-1602179237813-b11f1ae6ff56?w=1200&h=800&fit=crop",
    badge: "Sol y Playa",
    rating: 4.4,
    bestTime: "Mayo - Octubre",
    avgFlightPrice: "55€",
    readTime: "5 min",
    keywords: ["hoteles en Faro", "hoteles Algarve", "playas Algarve", "dónde dormir Algarve"],
  },

  // ── Bélgica ──
  {
    type: "city",
    name: "Bruselas",
    slug: "bruselas",
    country: "Bélgica",
    countrySlug: "belgica",
    continent: "Europa",
    continentSlug: "europa",
    short: "Chocolate, cerveza y la Grand Place más bella del mundo.",
    description: "Bruselas fusiona lo histórico con lo contemporáneo. Su Grand Place declarado Patrimonio de la Humanidad, sus chocolates artesanales y cervezas trapistas la convierten en un destino único.",
    whatToSee: ["Grand Place y Atomium", "Manneken Pis", "Museo de los Cómics", "Sablon y Notre-Dame"],
    gastronomy: ["Chocolate artesanal", "Waffles belgas", "Cervezas trapistas", "Mejillones con patatas fritas"],
    activities: ["Tour de chocolates", "Cata de cervezas belgas", "Ruta de cómics murales", "Visitar Atomium"],
    priceRange: "80€ - 160€",
    image: "https://images.unsplash.com/photo-1533387520709-752d83de3630?w=1200&h=800&fit=crop",
    rating: 4.4,
    bestTime: "Marzo - Octubre",
    avgFlightPrice: "90€",
    readTime: "6 min",
    keywords: ["hoteles en Bruselas", "dónde dormir en Bruselas", "hoteles baratos Bruselas"],
  },

  // ─────────────────────────────────────
  // ASIA
  // ─────────────────────────────────────

  // ── Japón ──
  {
    type: "country",
    name: "Japón",
    slug: "japon",
    country: "Japón",
    countrySlug: "japon",
    continent: "Asia",
    continentSlug: "asia",
    short: "Tradición milenaria y tecnología puntera en perfecta armonía.",
    description: "Japón es un país fascinante donde templos antiguos conviven con rascacielos futuristas. Desde Tokio hasta Kioto, pasando por Osaka y el Monte Fuji, ofrece una experiencia cultural sin igual.",
    whatToSee: ["Templo Senso-ji en Tokio", "Fushimi Inari en Kioto", "Castillo de Himeji", "Monte Fuji y Hakone"],
    gastronomy: ["Sushi y sashimi", "Ramen tonkotsu", "Kaiseki ryori", "Matcha y wagashi"],
    activities: ["Ceremonia del té", "Onsen tradicional", "Tour de templos en Kioto", "Comprar en Shibuya"],
    priceRange: "70€ - 200€",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&h=800&fit=crop",
    badge: "Top",
    rating: 4.9,
    bestTime: "Marzo - Mayo",
    avgFlightPrice: "600€",
    readTime: "12 min",
    keywords: ["hoteles en Japón", "viajar a Japón", "destinos Japón"],
    cities: ["tokio", "kioto", "osaka"],
  },
  {
    type: "city",
    name: "Tokio",
    slug: "tokio",
    country: "Japón",
    countrySlug: "japon",
    continent: "Asia",
    continentSlug: "asia",
    parentSlug: "japon",
    short: "Neón, templos y la ciudad más fascinante del futuro.",
    description: "Tokio es una metrópoli donde la tradición milenaria convive con la tecnología más puntera. Desde templos antiguos como Senso-ji hasta el neón de Shibuya, ofrece experiencias que no se encuentran en ningún otro lugar del mundo.",
    whatToSee: ["Senso-ji y Asakusa", "Shibuya Crossing", "Meiji Jingu", "Tokyo Skytree"],
    gastronomy: ["Sushi en Toyosu Market", "Ramen en Shinjuku", "Kaiseki", "Izakayas en callejones"],
    activities: ["Explorar templos al amanecer", "Shopping en Ginza", "Karaoke en Shinjuku", "TeamLab"],
    priceRange: "80€ - 200€",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&h=800&fit=crop",
    badge: "Top",
    rating: 4.9,
    bestTime: "Marzo - Mayo",
    avgFlightPrice: "600€",
    readTime: "10 min",
    keywords: ["hoteles en Tokio", "dónde dormir en Tokio", "hoteles baratos Tokio"],
  },
  {
    type: "city",
    name: "Kioto",
    slug: "kioto",
    country: "Japón",
    countrySlug: "japon",
    continent: "Asia",
    continentSlug: "asia",
    parentSlug: "japon",
    short: "Templos, geishas y jardines zen en el corazón de Japón.",
    description: "Kioto es el alma cultural de Japón. Con más de 2000 templos, santuarios shinto y jardines zen, es el destino perfecto para entender la esencia de la cultura japonesa. El barrio de Gion y sus geishas completan la experiencia.",
    whatToSee: ["Fushimi Inari y sus torii", "Kinkaku-ji (Pabellón Dorado)", "Barrio de Gion y geishas", "Bamboo Grove de Arashiyama"],
    gastronomy: ["Kaiseki ryori tradicional", "Yudofu y tofu", "Matcha green tea", "Kyo-ryori y wagashi"],
    activities: ["Ceremonia del té", "Paseo por el Camino de los Filósofos", "Kimono experience en Gion", "Visita a templos al amanecer"],
    priceRange: "70€ - 180€",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&h=800&fit=crop",
    rating: 4.9,
    bestTime: "Marzo - Mayo",
    avgFlightPrice: "650€",
    readTime: "8 min",
    keywords: ["hoteles en Kioto", "dónde dormir en Kioto", "templos Kioto", "turismo Kioto"],
  },
  {
    type: "city",
    name: "Osaka",
    slug: "osaka",
    country: "Japón",
    countrySlug: "japon",
    continent: "Asia",
    continentSlug: "asia",
    parentSlug: "japon",
    short: "La cocina de Japón con un castillo imperial y vida nocturna.",
    description: "Osaka es conocida como la cocina de Japón. Su castillo imperial, el barrio de Dotonbori con sus neones y la comida callejera la convierten en un destino vibrante y delicioso.",
    whatToSee: ["Castillo de Osaka", "Dotonbori y neones", "Universal Studios Japan", "Shinsekai y Tsutenkaku"],
    gastronomy: ["Takoyaki (bolas de pulpo)", "Okonomiyaki", "Kushikatsu", "Sushi en el mercado"],
    activities: ["Tour gastronómico por Dotonbori", "Universal Studios", "Paseo en barco por Dotonbori", "Visita a Nara desde Osaka"],
    priceRange: "60€ - 160€",
    image: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&h=800&fit=crop",
    rating: 4.5,
    bestTime: "Marzo - Mayo",
    avgFlightPrice: "580€",
    readTime: "6 min",
    keywords: ["hoteles en Osaka", "dónde dormir en Osaka", "comida Osaka", "turismo Osaka"],
  },

  // ─────────────────────────────────────
  // AMÉRICA
  // ─────────────────────────────────────

  // ── Estados Unidos ──
  {
    type: "country",
    name: "Estados Unidos",
    slug: "estados-unidos",
    country: "Estados Unidos",
    countrySlug: "estados-unidos",
    continent: "América",
    continentSlug: "america",
    short: "Rascacielos, parques nacionales y el sueño americano.",
    description: "Estados Unidos es un país de contrastes. Desde los rascacielos de Nueva York hasta los parques nacionales del oeste, pasando por las playas de California y la cultura sureña, ofrece una variedad inagotable.",
    whatToSee: ["Estatua de la Libertad", "Gran Cañón", "Golden Gate Bridge", "Times Square y Broadway"],
    gastronomy: ["Hamburguesas y BBQ", "Pizza de Nueva York", "Clam chowder y lobster roll", "Craft beer y bourbon"],
    activities: ["Show en Broadway", "Ruta por parques nacionales", "Road trip por la Ruta 66", "Compras en Nueva York"],
    priceRange: "100€ - 350€",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&h=800&fit=crop",
    rating: 4.6,
    bestTime: "Abril - Junio",
    avgFlightPrice: "450€",
    readTime: "12 min",
    keywords: ["hoteles en Estados Unidos", "viajar a Estados Unidos", "destinos Estados Unidos"],
    cities: ["nueva-york", "miami"],
  },
  {
    type: "city",
    name: "Nueva York",
    slug: "nueva-york",
    country: "Estados Unidos",
    countrySlug: "estados-unidos",
    continent: "América",
    continentSlug: "america",
    parentSlug: "estados-unidos",
    short: "La ciudad que nunca duerme: rascacielos, Broadway y Central Park.",
    description: "Nueva York es un universo en una ciudad. Manhattan con sus icónicos rascacielos, Central Park como oasis urbano, Broadway con sus shows de clase mundial ofrecen experiencias para todos.",
    whatToSee: ["Estatua de la Libertad", "Empire State Building", "Central Park y Metropolitan", "Times Square y Broadway"],
    gastronomy: ["Pizza de Nueva York", "Bagels y lox", "Pastrami en Katz's", "Comida callejera multicultural"],
    activities: ["Show de Broadway", "Caminar por Brooklyn Bridge", "Picnic en Central Park", "Museo Metropolitano"],
    priceRange: "150€ - 350€",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&h=800&fit=crop",
    rating: 4.7,
    bestTime: "Abril - Junio",
    avgFlightPrice: "500€",
    readTime: "9 min",
    keywords: ["hoteles en Nueva York", "dónde dormir en Nueva York", "hoteles Manhattan"],
  },
  {
    type: "city",
    name: "Miami",
    slug: "miami",
    country: "Estados Unidos",
    countrySlug: "estados-unidos",
    continent: "América",
    continentSlug: "america",
    parentSlug: "estados-unidos",
    short: "Playas, art déco y la vibrante cultura latina de Florida.",
    description: "Miami es la ciudad del sol eterno. Sus playas de South Beach, la arquitectura art déco, la explosión de color de Little Havana y el arte del Wynwood Walls crean una atmósfera única entre Estados Unidos y Latinoamérica.",
    whatToSee: ["South Beach y Ocean Drive", "Wynwood Walls", "Little Havana", "Vizcaya Museum"],
    gastronomy: ["Cuban sandwich y café cubano", "Ceviche y comida latina", "Stone crab", "Mojitos y ron"],
    activities: ["Día de playa en South Beach", "Tour de arte en Wynwood", "Calle Ocho y salsa cubana", "Excursión a los Everglades"],
    priceRange: "120€ - 280€",
    image: "https://images.unsplash.com/photo-1514214246283-d427a95c5d2f?w=1200&h=800&fit=crop",
    badge: "Sol y Playa",
    rating: 4.5,
    bestTime: "Noviembre - Mayo",
    avgFlightPrice: "450€",
    readTime: "7 min",
    keywords: ["hoteles en Miami", "dónde dormir en Miami", "hoteles playa Miami", "hoteles South Beach"],
    transport: "Alquiler de coche recomendado. Autobús (Metrobus) y Metrorail cubren Miami. El aeropuerto (MIA) conecta por autobús y tren (Metrorail). Uber/Lyft son muy usados. Miami Beach tiene un trolley gratuito.",
    travelTips: ["South Beach es ideal temprano para evitar el calor y las multitudes", "Little Havana tiene los mejores cafés cubanos y la mejor música en vivo", "Wynwood Walls es gratuito y cambia constantemente", "Los Everglades merecen un día completo, mejor con tour guiado", "El tráfico en Miami es intenso, evita las horas punta"],
    neighborhoods: [
      { name: "South Beach", desc: "La zona más icónica con playas, art déco, restaurantes y vida nocturna." },
      { name: "Downtown Miami", desc: "Centro financiero con Brickell, museos y la mejor gastronomía." },
      { name: "Little Havana", desc: "Calle Ocho, cultura cubana, tabaquerías y el mejor café cubano." },
      { name: "Coconut Grove", desc: "Barrio bohemio con tiendas, restaurantes al aire libre y marina." },
    ],
    dayTrips: ["Everglades - Pantanos y caimanes a 1h", "Key West - Islas paradisíacas a 3.5h"],
    budget: "Económico: 90€/día. Medio: 180€/día. Lujo: 400€+/día (temporada alta diciembre-abril).",
  },
];

export const continents = [...new Set(destinations.map((d) => d.continent))];
export const countries = [...new Set(destinations.filter((d) => d.type === "country").map((d) => d.name))];

export function getDestinationsByContinent(continent: string) {
  return destinations.filter((d) => d.continent.toLowerCase() === continent.toLowerCase());
}

export function getDestinationsByCountry(country: string) {
  return destinations.filter((d) => d.country.toLowerCase() === country.toLowerCase());
}

export function getDestinationBySlug(slug: string) {
  return destinations.find((d) => d.slug === slug);
}

export function getCitiesByCountry(countrySlug: string) {
  return destinations.filter((d) => d.parentSlug === countrySlug);
}

export function getContinentSlug(continent: string) {
  return continent.toLowerCase().replace(/ /g, "-");
}

export function getCountrySlug(country: string) {
  return country.toLowerCase().replace(/ /g, "-");
}
